source :rubygems
gem 'sinatra'
gem 'haml'
gem 'sqlite3-ruby'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'omniauth'
gem 'omniauth-identity'

group :development, :test do
  gem 'pry'
  gem 'shotgun'
end